// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Day1_dataJs from "./data/day1_data.js";

var data = Day1_dataJs.data;

console.log(data);

export {
  data ,
  
}
/* data Not a pure module */
