// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Helper from "./Helper.bs.js";

function processInput(input) {
  return Helper.NumSys.hexToBin(input);
}

function solve1(input) {
  console.log(input);
  
}

var data = Helper.Input.read("./src/data/input_day16.txt");

var ex1 = "38006F45291200";

var input = Helper.NumSys.hexToBin(ex1);

console.log(input);

export {
  processInput ,
  solve1 ,
  data ,
  ex1 ,
  input ,
  
}
/* data Not a pure module */
