// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Helper from "./Helper.bs.js";

function processInput(input) {
  return Helper.Input.toLines(input);
}

function solve1(input) {
  console.log(input);
  
}

var data = Helper.Input.read("./src/data/input_day19.txt");

var ex1 = "--- scanner 0 ---\n0,2\n4,1\n3,3\n\n--- scanner 1 ---\n-1,-1\n-5,0\n-2,1";

var input = Helper.Input.toLines(ex1);

console.log(input);

export {
  processInput ,
  solve1 ,
  data ,
  ex1 ,
  input ,
  
}
/* data Not a pure module */
