// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "../node_modules/rescript/lib/es6/belt_Int.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as Day1_dataJs from "./data/day1_data.js";

var raw = Day1_dataJs.data;

var data = Belt_Array.mapU(raw.split("\n"), (function (str) {
        return Belt_Option.getExn(Belt_Int.fromString(str));
      }));

var increases = Belt_Array.keepWithIndexU(data, (function (n, i) {
        var nPrev = Belt_Array.get(data, i - 1 | 0);
        if (nPrev !== undefined) {
          return n > nPrev;
        } else {
          return false;
        }
      }));

var incrCount = increases.length;

console.log(increases, incrCount);

var sample = "199\n200\n208\n210\n200\n207\n240\n269\n260\n263";

export {
  raw ,
  sample ,
  data ,
  increases ,
  incrCount ,
  
}
/* raw Not a pure module */
